config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations', omniauth_callbacks: "omniauth_callbacks" }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get :rewards, to: "main#rewards"
  post :redeem_reward, to: "main#redeem_reward"
  root to: "main#index"
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/coupon.rb
class Coupon < ActiveRecord::Base
  extend CommonUtils
  belongs_to :user
  belongs_to :reward
  has_one :reward_point_transaction, dependent: :destroy
  validates_presence_of :expires_at, :points, :code, :reward, :user, :reward_point_transaction
  validates_uniqueness_of :code

  before_validation do
    self.code = self.class.new_code if self.code.blank?
    unless reward_point_transaction
      #Add -ve transaction to user
      self.reward_point_transaction = RewardPointTransaction.new(user: user, title: "Redeemed #{self.points} points for #{reward.name} coupon", points: -self.points)
    end
  end

  def title
    code
  end

  def self.new_code
    generate_unique_code size: 8, charset: [(0..9),('A'..'Z')].map{|i| i.to_a}.flatten
  end
end

app/models/reward.rb
class Reward < ActiveRecord::Base
  validates_presence_of :name, :points, :background_color, :font_color
  has_many :coupons

  searchable do
    text :name
    text :description
    integer :points
  end

end

app/models/reward_point_transaction.rb
class RewardPointTransaction < ActiveRecord::Base
  belongs_to :user
  #TODO handle rails recursive dependent delete issue
  belongs_to :coupon
  validates_presence_of :title, :points, :user
end

app/models/settings.rb
class Settings < Settingslogic
  source "#{Rails.root}/config/application.yml"
  namespace Rails.env
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  AUTH_PROVIDER = [:facebook, :google_oauth2]

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: AUTH_PROVIDER
  validates_presence_of :name

  has_many :reward_point_transactions, -> { order 'created_at desc' }
  has_many :coupons, -> { order 'created_at desc' }

  def self.from_omniauth(auth)
    where(email: auth.info.email).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
      user.image_url = auth.info.image
    end
  end

  def points
    reward_point_transactions.sum :points
  end

  def as_json(options = { })
    super({methods: [:points]}.merge(options))
  end

  def redeem reward
    error = nil
    if reward
      if self.points >= reward.points
        coupon = Coupon.create(user: self, reward: reward, expires_at: (DateTime.now + 1.month), points: reward.points)
        unless coupon.valid?
          error = coupon.errors.full_messages
        end
      else
        error = I18n.t("user_redeem_errors.not_enough_points")
      end
    else
      error = I18n.t("user_redeem_errors.nil_reward")
    end
    error
  end

  def image_url
    img_url = read_attribute(:image_url)
    img_url.present? ? img_url : "https://lh3.googleusercontent.com/-XdUIqdMkCWA/AAAAAAAAAAI/AAAAAAAAAAA/4252rscbv5M/w200-h200/photo.jpg"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  respond_to :json, :html

  def render_404
    respond_to do |format|
      format.html { render :file => "#{Rails.root}/public/404", :layout => false, :status => :not_found }
      format.xml  { head :not_found }
      format.any  { head :not_found }
    end
  end

  def redirect_to_back(options)
    default = options.delete(:default) || root_url
    if request.env["HTTP_REFERER"].present? and request.env["HTTP_REFERER"] != request.env["REQUEST_URI"]
      redirect_to :back, options
    else
      redirect_to default, options
    end
  end
end

app/controllers/main_controller.rb
require "object_benchmark"
class MainController < ApplicationController
  before_action :authenticate_user!
  PER_PAGE = 16

  def index
    @coupons = current_user.coupons.includes(:reward)
  end

  def rewards
    @page = params[:page] || 1
    @query = params[:query]
    @rewards = if @query.blank?
      Reward.page(@page).per(PER_PAGE)
    else
      q = @query
      p = @page
      Sunspot.search(Reward) do
        fulltext("\"#{q}\"^5 OR #{q}~1") do
          boost_fields name: 2.0
        end
        paginate page: p, per_page: PER_PAGE
      end.results
    end
    respond_to do |format|
      format.html
      format.json {render json: @rewards}
    end
  end

  def redeem_reward
    respond_to do |format|
      if params[:reward_id].present?
        reward = Reward.find(params[:reward_id])
        result = ObjectBenchmark.new(current_user).redeem(reward)
        unless result
          format.html { redirect_to_back(default: rewards_path, notice: "#{reward.name} coupon is successfully redeemed, checkout your profile more for details")}
          format.json {render json: {message: "#{reward.name} coupon is successfully redeemed"}}
        else
          format.html {redirect_to_back(default: rewards_path, flash: {error: result})}
          format.json {render json: {error: result}, status: :bad_request}
        end
      else
        format.html { render_404}
        format.json {render json: {error: "Required parameter missing"}, status: :not_found}
      end
    end
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  #Dynamic handling of all provider. No need to declare different method for each provider
  def action_missing(name)
    if User::AUTH_PROVIDER.include?(name.to_sym)
      @user = User.from_omniauth(request.env["omniauth.auth"])
      if @user.persisted?
        sign_in_and_redirect @user, event: :authentication
      else
        session["devise.#{name}_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
  def active_class_name path
    request.path == path ? "active" : ""
  end

  def error_messages(msg)
    ret = "<ul>"
    if msg.is_a? Array
      if msg.length > 1
        msg.each do |m|
          ret += "<li>#{m}</li>"
        end
      else
        ret += "#{msg[0]}"
      end
    elsif msg.is_a? Hash
      msg.each do |k,v|
        ret += "<li>#{k}: #{v}</li>"
      end
    else
      ret += "#{msg}"
    end
    ret += "</ul>"
    raw(ret)
  end
end

app/views/layouts/_flash_messages.slim
- if flash[:success].present? || flash[:warn].present? || flash[:error].present? || flash[:alert].present? || flash[:notice].present?
  #flash-messages.flash-message-block
    - if flash[:success].present?
      .alert.alert-success.text-center
        button.close aria-hidden="true" data-dismiss="alert" type="button"
          = "&times;".html_safe
        = error_messages(flash[:success])
    - if flash[:warn].present?
      .alert.alert-warning.alert-dismissable.text-center
        button.close aria-hidden="true" data-dismiss="alert" type="button"
          = "&times;".html_safe
        = error_messages(flash[:warn])
    - if flash[:error].present?
      .alert.alert-danger.alert-dismissable.text-center
        button.close aria-hidden="true" data-dismiss="alert" type="button"
          = "&times;".html_safe
        = error_messages(flash[:error])
    - if flash[:alert].present?
      .alert.alert-info.alert-dismissable.text-center
        button.close aria-hidden="true" data-dismiss="alert" type="button"
          = "&times;".html_safe
        = error_messages(flash[:alert])
    - if flash[:notice].present?
      .alert.alert-info.alert-dismissable.text-center
        button.close aria-hidden="true" data-dismiss="alert" type="button"
          = "&times;".html_safe
        = error_messages(flash[:notice])

app/views/layouts/_navbar.slim
nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed aria-expanded="false" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      =link_to("Reward System", root_path, class: "navbar-brand")
    - if current_user
      #bs-example-navbar-collapse-1.collapse.navbar-collapse
        ul.nav.navbar-nav
          li class=(active_class_name(root_path))
            =link_to("Account", root_path)
          li class=(active_class_name(rewards_path))
            =link_to("Buy rewards", rewards_path)
        ul.nav.navbar-nav.navbar-right
          li= link_to "Sign out", destroy_user_session_path, method: :delete

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport" /
    title = (@title||"Reward System")
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = render partial: 'layouts/flash_messages'
    = render partial: 'layouts/navbar'
    .main-container
      .container-fluid
        = yield
    = render partial: 'layouts/footer'

app/views/main/_profile.slim
.panel.panel-default
  .panel-body
    .profile
      =image_tag(current_user.image_url, class: "img-circle")
      h3=current_user.name
      p=current_user.email
      p="Points: #{current_user.points}"

app/views/main/_reward_point_transactions.slim
- if current_user.reward_point_transactions.count > 0
  hr
  h4 Reward point transactions
  table.table
    tr
      td #
      td Title
      td Points
    - current_user.reward_point_transactions.each do |rpt|
      tr class=(rpt.points > 0 ? "success" : "danger")
        td="##{rpt.id}"
        td="#{rpt.title}"
        td="#{rpt.points}"

app/views/main/index.html.slim
.row
  .col-md-3= render partial: 'main/profile'
  .col-md-6
    .panel.panel-default
      .panel-body
        .jumbotron
          h1="Hello, #{current_user.name.split(" ")[0]}..."
          - if current_user.points > 0
            p
              | You have&nbsp;
              strong= current_user.points
              | &nbsp;points in your account. Redeem it fast and get shopping vouchers, coupons and etc.
            p=link_to("Redeem it now", rewards_path, class: "btn btn-primary btn-lg")
          - else
            p
              | You don't have enough points in your account. Please ask admin to credit some points. Later you can unlock millions of coupon and voucher from the gallery
        = render partial: 'main/reward_point_transactions'
  .col-md-3
    .panel.panel-default
      .panel-heading My Coupons
      - if @coupons.count > 0
        ul.list-group
          - @coupons.each do |c|
            li.list-group-item.coupons
              .branding style=("background: #{c.reward.background_color}; color: #{c.reward.font_color};")
                =c.reward.name
              span.badge =c.code
              span.badge ="#{c.points} pts"
              br
              .small.pull-right ="Use by #{c.expires_at.to_date}"
      - else
        .panel-body
          p You don't have any redeemed coupon !!!

app/views/main/rewards.slim
.row.rewards
  .col-md-3= render partial: 'main/profile'
  .col-md-9
    .row
      .col-md-6.col-md-offset-3
        form action=(rewards_path)
          .input-group
            input.form-control.input-lg placeholder=("Search for...") type="text" name="query" autocomplete="off" value=(@query)
            span.input-group-btn
              button.btn.btn-default.btn-lg type="submit"  Search
        br
    - if @rewards.count > 0
      .row
        - @rewards.each do |r|
          .col-md-3
            .panel.panel-default.reward
              .branding style=("background: #{r.background_color}; color: #{r.font_color};") title=(r.description)
                =r.name
              .info
                .points="#{r.points}pts"
                - if r.points <= current_user.points
                  = link_to "Redeem", redeem_reward_path(reward_id: r.id), method: :post, data: {confirm: "Are you sure, click ok to confirm?"} , class: "btn btn-default btn-sm"
                - else
                  a.btn.btn-default.btn-sm disabled="disabled" title="You don't have enough points to redeem this coupon" Redeem
      .pull-right
        = paginate @rewards, :theme => 'twitter-bootstrap-3'
    - else
      .row
        .col-md-6.col-md-offset-3
          br
          br
          br
          h3 Oopss... no result found